# NeuralNetwork Class Definition

In [5]:
import numpy as np
from scipy.special import expit

In [6]:
class NeuralNetwork:
    # Initialize the Neural Network
    def __init__(self, input, hidden, output, learning_rate):
        # Set the parameters
        self.input_nodes = input
        self.hidden_nodes = hidden
        self.output_nodes = output
        self.learning_rate = learning_rate

        # Set the Weight Matrix for Input-Hidden (w_i_h): w_i_j from node i in input_layer to node j in hidden_layer
        # Rows : Number of Neurons in the Hidden Layer
        # Columns : Number of Neurons in the Input Layer
        # self.w_i_h = np.random.rand(self.hidden_nodes, self.input_nodes) - 0.5
        # Using normal distribution, random.generator.normal
        self.w_i_h = np.random.default_rng().normal(0,                            # mu = 0   
                                                    pow(self.input_nodes, -0.5),  # sigma(standard deviation) = 1/(number of input neurons)^0.5
                                                    (self.hidden_nodes, self.input_nodes))  # output shape        
        
        #Set the Weight Matrix for Hidden-Output (w_h_o): w_i_j from node i in hidden_layer to node j in output_layer
        #self.w_h_o = np.random.rand(self.output_nodes, self.hidden_nodes) - 0.5
        self.w_h_o = np.random.default_rng().normal(0,                            # mu = 0   
                                                    pow(self.hidden_nodes, -0.5),  # sigma(standard deviation) = 1/(number of input neurons)^0.5
                                                    (self.output_nodes, self.hidden_nodes))  # output shape    

        self.activation_function = lambda x : expit(x)


    
    # Query the Neural Network --- Feed Forward
    def query(self, input_list):
        inputs = np.array(input_list, ndmin = 2).T
        x_hidden = np.dot(self.w_i_h, inputs)
        o_hidden = self.activation_function(x_hidden)

        x_output = np.dot(self.w_h_o, o_hidden)
        o_output = self.activation_function(x_output)

        return o_output



    # Train the Neural Network --- Back Propagation
    def train(self, input_list, target_list):
        # calculating outputs in Hidden and Output Layers
        inputs = np.array(input_list, ndmin = 2).T
        x_hidden = np.dot(self.w_i_h, inputs)
        o_hidden = self.activation_function(x_hidden)

        x_output = np.dot(self.w_h_o, o_hidden)
        o_output = self.activation_function(x_output)

        
        # calculating Errors by differentiating between Target and Output
        targets = np.array(target_list, ndmin = 2).T
        output_errors = targets - o_output
        
        # Errors on the Hidden Layer
        hidden_errors = np.dot(self.w_h_o.T, output_errors)

        # Back Propogation and calculating new Weights
        self.w_h_o += self.learning_rate * np.dot((output_errors * o_output * (1 - o_output)) , o_hidden.T)
        self.w_i_h += self.learning_rate * np.dot((hidden_errors * o_hidden * (1 - o_hidden)) , inputs.T)

        
        

In [ ]:
## Test

mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.default_rng().normal(mu, sigma, 1000)
# abs(mu - np.mean(s))
# abs(sigma - np.std(s, ddof=1))
import matplotlib.pyplot as plt
count, bins, ignored = plt.hist(s, 30, density=True)
plt.plot(bins, 1/(sigma * np.sqrt(2 * np.pi)) *
               np.exp( - (bins - mu)**2 / (2 * sigma**2) ),
         linewidth=2, color='r')
plt.show()

# Neural Network Instance Creation

In [7]:
# Number of Nodes in each Layer & Learning Rate
input_nodes = 3
hidden_nodes = 3
output_nodes = 3
learning_rate = 0.3

nn = NeuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)
print("Weight matix for input -> hidden")
print(nn.w_i_h)
print("Mean: ", np.mean(nn.w_i_h))
print("Standard Deviation: ", np.std(nn.w_i_h))
print("\nWeight matix for hidden -> output")
print(nn.w_h_o)

input = [0.1 , 0.2 , 0.3]
target = [0.22 , 0.55 , 0.99]

print("\nFirst Output")
print(nn.query(input))






Weight matix for input -> hidden
[[-0.92951388  0.70031828  0.47939828]
 [-0.31907819 -0.24597218  0.51655163]
 [ 0.22431205 -0.53056127  0.49101758]]
Mean:  0.04294136586812299
Standard Deviation:  0.5343445634871387

Weight matix for hidden -> output
[[-0.2160873  -0.3977469  -0.05359885]
 [-0.31720321 -0.23974736  1.30403686]
 [-0.04876459  0.17065015  1.01616687]]

First Output
[[0.41285062]
 [0.59260815]
 [0.64244984]]


In [8]:
#try_1 = nn.train(input, target)

#print("Weight matix for input -> hidden")
#print(nn.w_i_h)
#print("\nWeight matix for hidden -> output")
#print(nn.w_h_o)

#print(nn.query(input).T)

for i in range (1,10001):
    nn.train(input, target)
    if(i%1000 == 0):
        print( i)
        print(nn.query(input).T)
    

1000
[[0.21834654 0.55027839 0.96631201]]
2000
[[0.21939757 0.55005427 0.97762854]]
3000
[[0.21967385 0.55001547 0.98185537]]
4000
[[0.21979257 0.5500043  0.98409996]]
5000
[[0.21985595 0.55000036 0.985497  ]]
6000
[[0.21989428 0.54999887 0.98644903]]
7000
[[0.21991944 0.54999834 0.98713674]]
8000
[[0.21993692 0.54999821 0.98765397]]
9000
[[0.2199496  0.54999826 0.98805456]]
10000
[[0.21995909 0.54999839 0.98837176]]
